name: deploy to heroku

on:
  push:
    branches: [dy-styles]

jobs:
  build_container_in_heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to heroku container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:login

      - name: set NODE_ENV variable
        run: heroku config:set NODE_ENV=production -a lending-app-codezilla

      - name: build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:push -a lending-app-codezilla web

      - name: build and release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:release -a lending-app-codezilla web
