name: test heroku envs

on:
  push:
    branches: [heroku]

jobs:
  heroku_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to heroku container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:login

      - name: build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}

        run: heroku container:push -a lending-app-codezilla web --arg REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY}},REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN}},REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID}},REACT_APP_FIREBASE_STORAGE_BCKT=${{ secrets.REACT_APP_FIREBASE_STORAGE_BCKT}},REACT_APP_FIREBASE_MSG_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MSG_SENDER_ID}},REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID}}

      - name: build and release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:release -a lending-app-codezilla web
