name: deploy to heroku

on:
  push:
    branches: [improvment]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to heroku container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:login

      # - name: set API
      #   run: heroku config:set REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }} -a lending-app-codezilla

      # - name: set AUTH-DOMAIN
      #   run: heroku config:set REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }} -a lending-app-codezilla

      # - name: set APP-ID
      #   run: heroku config:set REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }} -a lending-app-codezilla

      # - name: set SENDER-ID
      #   run: heroku config:set REACT_APP_FIREBASE_MSG_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MSG_SENDER_ID }} -a lending-app-codezilla

      # - name: set PROJECT-ID
      #   run: heroku config:set REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }} -a lending-app-codezilla

      # - name: set STORAGE-BUCKET
      #   run: heroku config:set REACT_APP_FIREBASE_STORAGE_BCKT=${{ secrets.REACT_APP_FIREBASE_STORAGE_BCKT }} -a lending-app-codezilla

      - name: build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:push -a lending-app-codezilla web --arg REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}

      - name: build and release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:release -a lending-app-codezilla web
